/* Progressive enhancement only: the base document remains usable without it. */
(() => {
  'use strict';
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
  const data=window.PORTFOLIO_DATA||{}, reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const pre=$('#preloader'), bar=$('#preloadBar'), count=$('#preloadCount');
  let p=0; const loader=setInterval(()=>{p=Math.min(100,p+17);bar.style.width=`${p}%`;count.textContent=String(p).padStart(2,'0');if(p===100){clearInterval(loader);setTimeout(()=>pre.classList.add('done'),120)}},90);
  setTimeout(()=>pre.classList.add('done'),1200);
  $('#heroRole').textContent=(data.role||'Video Editor & Motion Designer').toUpperCase(); $('#heroLocation').textContent=(data.location||'India').toUpperCase(); $('#year').textContent=new Date().getFullYear();
  const name=$('#heroName'); if(data.name) name.textContent=data.name.toUpperCase();
  if(!reduced && name){name.innerHTML=[...name.textContent].map(x=>`<span class="char">${x}</span>`).join('');}
  const email=$('#contactEmail'); if(data.email){email.textContent=data.email;email.href=`mailto:${data.email}`;}
  const social=[data.socials?.instagram,data.socials?.youtube,data.socials?.linkedin]; $$('.social').forEach((a,i)=>{if(social[i]&&social[i]!=='#'){a.href=social[i];a.target='_blank';a.rel='noopener';}});
  let words=data.heroWords||['hook viewers'], word=0; if(!reduced) setInterval(()=>{$('#rotator').textContent=words[word=++word%words.length];},2600);
  const modal=$('#modal'), player=$('#modalPlayer'); function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');player.replaceChildren();document.body.style.overflow='';} function open(card){const source=data.videos?.[card.dataset.key]||{};$('#modalTitle').textContent=card.querySelector('h3').textContent;$('#modalCat').textContent=card.querySelector('.mono').textContent;player.replaceChildren();let node;if(source.type==='iframe'){node=document.createElement('iframe');node.src=source.url;node.title=$('#modalTitle').textContent;node.allow='autoplay; fullscreen; encrypted-media; picture-in-picture';node.allowFullscreen=true;}else{node=document.createElement('video');node.src=source.url||card.dataset.key;node.controls=true;node.playsInline=true;}player.append(node);modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
  $$('.work-card').forEach(card=>card.addEventListener('click',()=>open(card)));$('.modal__close').addEventListener('click',close);$('.modal__backdrop').addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});
  $$('#filters button').forEach(btn=>btn.addEventListener('click',()=>{const f=btn.dataset.filter;$$('#filters button').forEach(x=>x.classList.toggle('active',x===btn));$$('.work-card').forEach(c=>c.classList.toggle('hidden',f!=='all'&&c.dataset.category!==f));}));
  const burger=$('#burger'), menu=$('#mobileMenu'); burger.addEventListener('click',()=>{const isOpen=menu.classList.toggle('open');burger.setAttribute('aria-expanded',isOpen);document.body.style.overflow=isOpen?'hidden':'';});$$('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');burger.setAttribute('aria-expanded','false');document.body.style.overflow='';}));
  const onScroll=()=>{$('#nav').classList.toggle('scrolled',scrollY>25);$('#progress').style.transform=`scaleX(${scrollY/(document.documentElement.scrollHeight-innerHeight)||0})`;};addEventListener('scroll',onScroll,{passive:true});onScroll();
  const timeline=$('#timeline'); if(timeline&&Array.isArray(data.timeline)){timeline.innerHTML='<div class="timeline__progress"></div>'+data.timeline.map(item=>`<article><span class="mono">${item.date}</span><h3>${item.title}</h3><h4>${item.org}</h4><p>${item.desc}</p><div class="timeline__tags">${item.tags.map(tag=>`<b>${tag}</b>`).join('')}</div></article>`).join('');}
  const observe=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed'); if(e.target.classList.contains('reveal')) e.target.style.cssText+='opacity:1;transform:none;transition:opacity .75s,transform .75s;'; observe.unobserve(e.target);}}),{threshold:.15});$$('.reveal,.timeline article').forEach(el=>observe.observe(el));
  const countObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=+el.dataset.count;if(reduced){el.textContent=target;return;}let start;const run=t=>{start??=t;const k=Math.min(1,(t-start)/1100);el.textContent=Math.round(target*(1-(1-k)**3));if(k<1)requestAnimationFrame(run);};requestAnimationFrame(run);countObs.unobserve(el);}),{threshold:.5});$$('.counter').forEach(el=>countObs.observe(el));
  const barObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.style.width=`${e.target.dataset.width}%`;barObs.unobserve(e.target);}}),{threshold:.5});$$('.bar i').forEach(el=>barObs.observe(el));
  if(window.gsap&&!reduced){gsap.registerPlugin(ScrollTrigger);gsap.from('.hero .char',{y:'115%',rotate:8,opacity:0,stagger:.07,duration:1.1,ease:'power4.out'});gsap.utils.toArray('.blob').forEach((b,i)=>gsap.to(b,{y:i?140:-120,scrollTrigger:{trigger:'#hero',scrub:true}}));gsap.to('.timeline__progress',{scaleY:1,ease:'none',scrollTrigger:{trigger:'#experience',start:'top 70%',end:'bottom 65%',scrub:true}});gsap.to('.showreel__inner',{xPercent:-18,scrollTrigger:{trigger:'.showreel',start:'top top',end:'+=100%',pin:true,scrub:true}});}
  if(!reduced&&matchMedia('(hover:hover) and (pointer:fine)').matches){const dot=$('#cursorDot'),ring=$('#cursorRing');let x=-100,y=-100,rx=-100,ry=-100;addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;dot.style.transform=`translate(${x}px,${y}px) translate(-50%,-50%)`},{passive:true});(function loop(){rx+=(x-rx)*.16;ry+=(y-ry)*.16;ring.style.transform=`translate(${rx}px,${ry}px) translate(-50%,-50%)`;requestAnimationFrame(loop)})();document.addEventListener('mouseover',e=>{if(e.target.closest('a,button,[data-magnetic]'))ring.classList.add('is-hover')});document.addEventListener('mouseout',e=>{if(e.target.closest('a,button,[data-magnetic]'))ring.classList.remove('is-hover')});$$('[data-magnetic]').forEach(el=>el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.16}px,${(e.clientY-r.top-r.height/2)*.16}px)`;}));$$('[data-magnetic]').forEach(el=>el.addEventListener('mouseleave',()=>el.style.transform=''));}
})();
